.eslintrc.json
mobile/babel.config.js

Adding config file for eslinter
---

ADD: Adding eslint config

---

.gitignore
web/.gitignore

Removed package.json file from gitignore per Ben's recommendation. Need to remove the lock one from repo.

Modified .gitignore

---

web/package-lock.json
web/package.json
web/src/App.js
web/src/components/Dashboard.js
web/src/components/Login.js
web/src/components/__tests__/dashboard.test.js
web/src/components/__tests__/login.test.js
web/src/components/__tests__/navbar.test.js
web/src/styles/dashboard.css

Completed the signin process. Given valid credential a user can now log in and will be redirected to a dashboard.
Login has been tested to ensure that a request is sent with the proper data to the proper port. 
The dashboard has also been test to ensure that the proper elements are rendered.
N/A
#8 #35 
One thing to note is that I had to allow jest to enable the axiom module otherwise the test wouldn't run and crash. 
package.json was modified
---

Adnane login 2

---

server/index.js
server/package.json
server/routes/UserRoutes.js
server/tests/UserRoutes.test.js
web/src/components/__tests__/navbar.test.js

Added API Routes to get, update and delete user data, tested routes thouroughly and achieved 95% coverage (This coverage is the highest possible, as the only lines not being hit are lines that need to be skipped durring testing mode)
Unit tested user routes, added 14 new tests
None
#54 #53 
---

ENH: Add backend user API routes

---

.github/workflows/testing.yml

This PR just adds a workflow for the new mobile tests added in @bdesollar's previous pr #56 
None
None
#57 #21 
---

ENH: Adding mobile testing workflow

---

package-lock.json
package.json
web/package-lock.json
web/package.json
web/src/App.js
web/src/components/Navbar.js
web/src/components/Signup.js
web/src/components/__tests__/signup.test.js
web/src/styles/signup.css

Created a Sign up page and connected to backend to be able to create a new account.
Testing the different elements on the page as well as the form submission.
#5 #32 
I tried to use react-toastify to create flash messages to user, however it would not load at all. As if the package is recognized but not loaded properly. Maybe corrupted ? 
---

Web: Account creation

---

.eslintignore
.github/workflows/testing.yml
babel.config.js
extension/.eslintrc.json
extension/__mocks__/chromeMock.js
extension/__mocks__/styleMock.js
extension/babel.config.js
extension/jest.config.js
extension/jest.setup.js
extension/package.json
extension/public/background.js
extension/public/contentScript.js
extension/public/manifest.json
extension/src/App.css
extension/src/App.js
extension/src/App.test.js
extension/src/__tests__/App.test.js
extension/yarn.lock
web/src/components/Login.js

This pr allows users to click login in the extension and be redirected to the webpage, once the user logs in on the browser, they will also be logged in in the extension. They can also log out.
unit tests for server
- #84 
- #85
- #86
---

ENH: Extension login

---

.eslintignore
web/package-lock.json
web/package.json
web/src/App.js
web/src/components/Dashboard.js
web/src/components/Preference.js
web/src/components/Signup.js
web/src/components/__tests__/preference.test.js
web/src/styles/signup.css

Designed the preferences choice on sign up, using a pop up window.
Toggles and ensuring correct API calls are fully tested.
MISSING TEST: Loading data from storageSession. Will open up a different PR.
You can access the preferences at /preference:
Pop up:
#66 #68 #47 
---

Update Preferences when logging in

---

server/models/UsersModel.js
server/routes/UserRoutes.js
server/tests/UserRoutes.test.js

This pr adds multiple backend api to facilitate frontend development
This adds 4 new api calls.
```javascript
const response = await axios.put('http://localhost:3002/user/update-task-frequency', {
username: username,
taskFrequency: 3000 //this is a integer in mili seconds,
});
```
```javascript
const response = await axios.put('http://localhost:3002/user/update-work-preferences', {
username: username,
workPreferences: "I work on software development" //this is a string describing what work the user does
});
```
```javascript
const response = await axios.put('http://localhost:3002/user/update-reading-preferences', {
username: username,
readingPreferences: "I want to read on software development" //this is a string describing what kind of books wants
});
``` …

Backend fill out preferences

---

web/src/components/Preference.js
web/src/components/__tests__/preference.test.js

Users can now fill in how often they want to be prompted with a task to complete. 
Testing the data value being sent to the database (millisecond) and the data displayed to user (HH:mm format).
On signup the pop up window has been updated:
Preference setting page also reflects the change in /preference :
#76 #77 
---

Fill in and Update Frequency of Tasks

---

web/src/components/Login.js

Fixing a bug related to app crashing on Login using wrong credentials
N/A
N/A
#95 
---

Fixing crash on login

---

mobile/__tests__/screens/Settings.test.js
mobile/components/CustomAlert.js
mobile/screens/Preferences.js
mobile/screens/Settings.js

This PR introduces updates to the `CustomAlert.js` component, enhancing its versatility and enabling it to support multiple use cases across the application. Previously, the `CustomAlert` was designed for simple message displays. With this update, it now supports multiple buttons, each with customizable text and action handlers, making it suitable for various scenarios, including confirmations and user decisions.
Additionally, the `Settings.js` page has been updated to incorporate a "Delete Account" option. This feature leverages the updated `CustomAlert` component to present users with a confirmation dialog before proceeding with the account deletion process. It's important to note that while the frontend integration for the delete account option is complete, the …

Custom Alert Update and Delete Account Frontend Mobile

---

.github/workflows/testing.yml
server/index.js
server/models/TaskModel.js
server/models/UsersModel.js
server/routes/TaskRoutes.js
server/routes/UserRoutes.js
server/tests/TaskModel.test.js
server/tests/TaskRoutes.test.js
server/tests/UserRoutes.test.js
server/tests/authRoutes.test.js
web/src/components/Dashboard.js

This pr updates the user  model to have `frozenBrowsing`, `lastFrozen` and `frozenUntil` parameters as well as an api to call them.
I also added a Tasks model and api with documentation below let me know if you have any questions
- #114 
- #105 
- #106 
- #115 
- #126 
I was running into issues wit the server tests and wanted to get this code out as soon as possible to not slow down development, Ill get back to this later but let me know if it's not working as expected
This documentation provides examples of how to call the newly introduced API routes for managing tasks within our application.
- **Endpoint:** `user/update-frozen-browsing`
- **Method:** `PUT`
- **Description:** Update a user's frozen browsing status including when it was last frozen and until when it will be frozen.
- …

Adding Task model and routes

---

web/src/components/Preference.js
web/src/components/__tests__/preference.test.js

I worked on dynamically creating inputs for users to fill in their work and reading preference when they toggle those tasks
- Tested the API calls are being made at proper time with correct value.
- Tested elements being rendered on toggle.
- Tested sad paths as well for both of the previous elements.
#74 #72 #73 #70 
---

Filling work and reading preferences

---

server/routes/TaskRoutes.js

Fixed minor error grabbing id in task api rputes

FIX: Fixed id parameter in task routes

---

.github/workflows/testing.yml
server/package.json
server/routes/UserRoutes.js
server/tests/TaskRoutes.test.js
server/tests/UserRoutes.test.js
server/tests/authRoutes.test.js

This pull request fixes the server tests that were previously failing due to the req.query change
Unit and manual testing
- #126

ENH: Update server tests

---

extension/__mocks__/chromeMock.js
extension/package.json
extension/public/background.js
extension/public/manifest.json
extension/src/App.js
extension/src/__tests__/App.test.js
extension/src/components/CountdownTimer.js
extension/src/setupTests.js
server/models/UsersModel.js
server/routes/UserRoutes.js
web/src/components/Login.js
web/src/components/RewardHistory.js
web/src/components/Tasks.js

The goal of this pull request was to make a visible GUI showing how much time is left until a task in the extension. Once the timer ends the page is redirected to the tasks page for the user to take a break and watch relaxing videos. Users cannot browse to other sites during tasks. After a task is finished, the timer restarts
unit and manual tests
- #121
- #122 
- #103 
- #104 
- #122 
---

Extension, View task duration, redirect on timer end, & web restart timer on break end

---

web/src/App.js
web/src/components/AuthContext.js
web/src/components/Navbar.js
web/src/components/ProtectedRoute.js

Added a security patch to prevent users from navigating to pages they do not have access to.
N/A
#138 
---

Page navigation security patch

---

server/index.js
server/jest.config.mjs
server/models/BooksModel.js
server/package.json
server/routes/BookRoutes.js
server/routes/UserRoutes.js
server/tests/BookRoutes.test.js
server/tests/authRoutes.test.js

Added google books api and created a new Books collection with Api
only use the /get-by-google-title api once when adding books, then save data to our db with the /create api and after that only call the /get-by-title api whenever you want to access books
You will need to get an api key from me and add it to your .env file before this works
wrote unit tests and tested manually with insomnia
NA
- #151 
- #145 
- #146 
- **Endpoint:** `/book/get-by-google-title`
- **Method:** `GET`
- **Description:** Fetch books from the Google Books API by their title.
- **Query Parameters:**
- `title`: The title of the book to search for.
- **Response:**
- `books`: Array of books matching the provided title.
- **Status Codes:**
- `200 OK`: Successful retrieval of books.
- `500 …

ENH: Adding books api and test functionality

---

extension/__mocks__/chromeMock.js
extension/public/background.js
extension/public/manifest.json
extension/src/__tests__/App.test.js
extension/src/components/CountdownTimer.js
extension/src/setupTests.js
server/models/BooksModel.js
server/routes/BookRoutes.js
web/package.json
web/src/App.js
web/src/assets/ListItem.css
web/src/components/AuthContext.js
web/src/components/DialogBox.js
web/src/components/Homepage.js
web/src/components/ListItem.js
web/src/components/Navbar.js
web/src/components/Notification.js
web/src/components/Preference.js
web/src/components/ProtectedRoute.js
web/src/components/ReadTask.js
web/src/components/RewardHistory.js
web/src/components/Signup.js
web/src/components/SubNavbar.js
web/src/components/Tasks.js
web/src/styles/ReadTask.css
web/src/styles/homepage.css
web/src/styles/login.css
web/src/styles/navbar.css
web/src/styles/signup.css
web/src/styles/tasks.css

Made an add books screen with books api to allow user to view and add books
- #153 
---

Web add books

---

web/src/components/BookCard.js
web/src/components/ProgressBar.js
web/src/components/ReadTask.js
web/src/components/__tests__/bookcard.test.js
web/src/components/__tests__/progressbar.test.js
web/src/components/__tests__/readtask.test.js
web/src/styles/ReadTask.css
web/src/styles/bookcard.css
web/src/styles/progressbar.css

Showing the user the books they are currently reading along with tier progress.
The progress bar as well as the book cards are fully tested.
#147 #148 
---

Display the user's book preference

---

web/package.json
web/src/components/BookCard.js
web/src/components/BookDetail.js
web/src/components/ReadTask.js
web/src/components/__tests__/bookdetail.test.js
web/src/styles/bookdetail.css

When a user clicks on one of the books they are reading, they can submit a summary for each chapter of that book.
Pop up element is fully tested.
#157 #160 
---

Book detail pop up

---

server/index.js
server/models/BooksModel.js
server/models/UsersModel.js
server/package.json
server/routes/BadgeRoute.js
server/routes/BookRoutes.js
server/routes/UserRoutes.js
server/tests/BookRoutes.test.js
server/tests/TaskRoutes.test.js
server/tests/UserRoutes.test.js

Added api functionality and tests for adding book summaries, xp points and badges
api docs:
**Description:** This endpoint updates the summary of a chapter for a user's associated book.
**Method:** `PUT`
**URL:** `/update-summary`
**Input:**
- `title`: Title of the book.
- `chapter`: Chapter number for which the summary is being updated.
- `summary`: New summary text for the chapter.
- `username`: Username of the user.
**Output:**
- `message`: A message indicating the success or failure of the update operation.
- `book`: The updated book object with the new chapter summary.
**Example Request Body:**
```json
{
"title": "Example Book",
"chapter": 3,
"summary": "This is a summary of chapter 3.",
"username": "example_user"
}
```
**Description:** This endpoint …

Backend api for badges, summaries and xp points

---

server/models/UsersModel.js
server/routes/UserRoutes.js
web/src/components/BoxComponent.js
web/src/components/Dashboard.js
web/src/components/DialogBox.js
web/src/components/Login.js
web/src/components/Signup.js
web/src/components/__tests__/BoxComponent.test.js
web/src/components/__tests__/authcontext.test.js
web/src/components/__tests__/dashboard.test.js
web/src/components/__tests__/dialogbox.test.js
web/src/components/__tests__/exercise.test.js
web/src/components/__tests__/login.test.js
web/src/components/__tests__/notification.test.js
web/src/components/__tests__/signup.test.js
web/src/components/__tests__/taskbreak.test.js
web/src/components/__tests__/tasks.test.js

Adding blacklisted webpage option
Unit and manual tests
- #217 
- #218 
- #219 
- #220 
---

ENH: Updating dashboard

---

server/routes/UserRoutes.js
web/src/components/BookDetail.js
web/src/components/BoxComponent.js
web/src/components/Dashboard.js
web/src/components/DialogBox.js
web/src/components/Navbar.js
web/src/components/Preference.js
web/src/components/ReadTask.js
web/src/components/UserInfo.js
web/src/components/__tests__/bookdetail.test.js
web/src/components/__tests__/dashboard.test.js
web/src/components/__tests__/dialogbox.test.js
web/src/components/__tests__/navbar.test.js
web/src/components/__tests__/readtask.test.js
web/src/components/__tests__/userinfo.test.js
web/src/styles/boxcomponent.css
web/src/styles/dashboard.css
web/src/styles/dialogbox.css
web/src/styles/userinfo.css

Added some of the user information to the dashboard. User can now update their password as well as their first and last name. Additional fields to update can easily be added alter on.
The UserInfo.js code is decently tested. The branch % is relatively low with 69.75%, need to look some more into it in a different issue.
Probably need to reorganize the display of elements on the dashboard. Need some UI tips.
- #229 
- #228 
- #227 
---

Dashboard elements

---

extension/public/background.js
server/routes/UserRoutes.js
web/src/components/Login.js

Reworked extension from scratch to make sure frozen->countdown->frozen cycle always works as well as screen redirection
Manual and unit
None
- #231 
---

ENH: Reworking extension

---

web/src/components/Dashboard.js
web/src/components/Tasks.js
web/src/styles/boxcomponent.css
web/src/styles/dashboard.css

New styling of dashboard after talking with the team and Curt. Some more styling might be needed. 
Fixed the Task Break to work seamlessly with the extension.
- #244 
- #237 
---

New Dashboard and Task Break fix

---

extension/public/background.js
extension/public/manifest.json
extension/src/App.js
web/package.json
web/src/App.js
web/src/components/Tasks.js
web/src/styles/tasks.css

This PR encompasses a series of updates aimed at refining the web extension, deploying updates to Hostinger for the production environment, and addressing general bug fixes in the web application and extension. These changes are designed to enhance functionality, improve user experience, and ensure stability in production.
- **Web Extension**: Updated logic and UI improvements to enhance interaction and performance.
- **Deployment on Hostinger**: Configured deployment settings to optimize the production environment on Hostinger, ensuring smoother operations and better resource management.
- **Bug Fixes**: Addressed various bugs reported in the web application and extension, improving reliability and user interaction.
- **Web Extension Enhancements**: To provide users with a more intuitive …

Enhance extension
